### ISSUE TITLE
?? SOLUTION to 122  (IE problem)  ??

### ISSUE THREAD

**Issue by dickschrauwen** [portier/portier-broker#123] opened 2016-11-30 17:41 UTC
Modified forward.mustache
```
<!DOCTYPE html>
<html>
  <head>
    <title>Portier &ndash; Forwarding...</title>
    <script src="/static/forward.js"></script>
  </head>
  <body>
    <form id="form" action="{{ redirect_uri }}" method="post">
      {{# params }}
        <input type="hidden" name="{{ name }}" value="{{ value }}">
      {{/ params }}
    </form>
	<!-- a very very simple solution to IE-problem (https://github.com/portier/portier-broker/issues/122) -->
	<!-- NOT tested -->
	<SCRIPT>
	  document.getElementById('form').submit();
	  // a (to my taste to complicated) alternative @ https://github.com/jfriend00/docReady 
	</SCRIPT>
	
  </body>
</html>

```

**Comment by onli** [comment] 2016-11-30 18:05
(reference to #122)

To just call it inline would most likely solve this, but I think inline JS is forbidden by our security headers.

But we can also solve it in /static/forward.js. One of two solution should work:

 1. Move the script element to the bottom and call the submit() directly, without wrapping it in an event for DomContentLoaded
 * Check whether that event already fired, by checking document.readyState == 'complete', as in https://github.com/onli/feedtragon/blob/11c5fc582f015f56f0bc8775dc3b40085dbb2929/public/main.js#L428

This assumes the problem is that DomContentLoaded was already executed when that JS is interpreted which is a likely problem with IE. But that is what needs to be tested. 

Regardless, we can't rely on the current foward.js, as it is bound to happen sometimes that the event was fired before. I got burned by that browser behaviour in two different projects already, should've noticed it before :/

**Comment by dickschrauwen** [comment] 2016-12-01 13:51
Javascript is not my mother tongue nor is RUST. Why don't POST the form directly to the receiving url?Would be simple in Python using http://docs.python-requests.org/en/master/  | $ pip install requests

**Comment by onli** [comment] 2016-12-01 13:56
Because you want the user to deliver the token via the browser, so that in the end he is directly on the page he  tried to login to.

I think you got the issue identified, and I'm pretty sure one of my two approaches will fix this. We just need someone to test it, which means running a patched broker and IE 11, if necessary in a VM. @stephank, might that maybe be easiest for you?

**Comment by dickschrauwen** [comment] 2016-12-01 14:03
Okay, I see. I'll be happy to test it (running several winboxes 7, 8, 10, can also test it on OSX, Tails/Tor (if I'm able to install Python3), Deb8-Jessy

**Comment by stephank** [comment] 2016-12-02 10:35
I just tried this on a Windows 7 VM with IE 11, downloaded from modern.ie, and it seems to work fine. Tried with the current public broker at broker.portier.io, and with current master branch.

I also tested with a real, up-to-date Windows 10 machine we have at the office, and it works in both IE 11 and Edge there.

So something else is up, but I'm not sure what. :/

**Comment by stephank** [comment] 2016-12-02 10:46
@dickschrauwen Can you check if the public demo works for you, on the setup where you see the issue? It's at: https://portier-demo.herokuapp.com/

**Comment by dickschrauwen** [comment] 2016-12-02 14:14
@stephank 
```
Tested  https://portier-demo.herokuapp.com/ 
chrome54 win7  :: You are now logged in as info@niceware.com  (via link)
ie11 win7      :: You are now logged in as dickschrauwen@gmail.com. (automatic)  how/why?
ie11 win7      :: You are now logged in as dikkie3s@yahoo.com.  (copy/paste 	code)
ie11 win7      :: You are now logged in as dickschrauwen@hotmail.com (via email link) 
Tor? tails2.4  :: You are now logged in as salvadorado2@protonmail.com (via email link) 
Tor? tails2.4  :: You are now logged in as salvadorado2@gmail.com. (automatic / logged in in gmail)
edge? win10    :: You are now logged in as zimizic@gmail.com (via google account)
ffox47 win10   :: You are now logged in as dirk@nicetolive.com (via email link)
ie11 win10     :: You are now logged in as dirk@nicetolive.com (via email link)
ie11 win10     :: You are now logged in as dikko@medolie.com  (via email link)

```

**Comment by stephank** [comment] 2016-12-02 14:19
@dickschrauwen So the redirect only fails when you try to run the demo locally?

I suppose both automatic logins are because you used a `@gmail.com` address which happened to be logged in at Google in that browser.

**Comment by dickschrauwen** [comment] 2016-12-02 15:02
@stephank Yes, locally the redirect stil fails when i run it locally in IE / chrome is OK

**Comment by dickschrauwen** [comment] 2016-12-02 15:04
>> So something else is up, but I'm not sure what. :/  ,  strange ....

**Comment by onli** [comment] 2016-12-02 15:16
Okay, at the very least we know the event timing is not the problem.

Maybe IE11 is blocking the redirect to localhost only? https://stackoverflow.com/questions/17415111/127-0-0-1-will-not-work-in-ie-11 suggests that there might be issues with the security model. If it were that, It'd be out of our hands.

**Comment by dickschrauwen** [comment] 2016-12-02 15:44
Anyway, i'm just going to migrate from Persona to Portier. Checked out Janrain and Stormpath but i dont like it

**Comment by dickschrauwen** [comment] 2016-12-02 16:50
I tried all 'solutions' in https://stackoverflow.com/questions/17415111/127-0-0-1-will-not-work-in-ie-11 . Didn't help.; forward/redirtect still fails in IE

**Comment by stephank** [comment] 2020-04-26 17:38
Hope you don't mind me closing this. See #122 and #204.

**Closed by stephank** 2020-04-26 17:38 UTC
